export const root: HTMLElement = document.querySelector('#root');
export const audioTrack: () => HTMLAudioElement = () => document.querySelector('audio');
export const menuStartBtn: () => HTMLElement = () => document.querySelector('.menu_start-btn');
export const menuMuteBtn: () => HTMLElement = () => document.querySelector('.menu__btn-mute');
export const homeBtn: () => HTMLElement = () => document.getElementById('home');
export const filterPageBtn: () => HTMLElement = () => document.getElementById('filter-page');
export const gamePageBtn: () => HTMLElement = () => document.getElementById('game-page');
export const filterCountRange: () => HTMLElement = () => document.getElementById('slider-count');
export const filterYearRange: () => HTMLElement = () => document.getElementById('slider-year');
export const favoriteFilter: () => HTMLElement = () => document.getElementById('favorite-filter');
export const countMin: () => HTMLElement = () => document.querySelector('.count-min');
export const countMax: () => HTMLElement = () => document.querySelector('.count-max');
export const yearMin: () => HTMLElement = () => document.querySelector('.year-min');
export const yearMax: () => HTMLElement = () => document.querySelector('.year-max');
